sudo: required
dist: trusty
addons:
  apt:
    packages:
      - cgroup-bin
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  matrix:
    # NOTE: We don't test 1.5, since it can't pull from the public registry.
    - DOCKER_VERSION=1.6.2
    - DOCKER_VERSION=1.7.1
    - DOCKER_VERSION=1.9.1
    - DOCKER_VERSION=1.11.2
install:
  - sudo wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.9/gosu-$(dpkg --print-architecture)"
  - sudo chmod +x /usr/local/bin/gosu
  - sudo chmod ug+s /usr/local/bin/gosu
  - gosu root .ci/install-docker.sh
  - gosu root make install
  - gosu root pip install -r test_requirements.txt
script:
  - docker run -i --rm alpine true
  - gosu root make test
